name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'Makefile'
      - 'scripts/**'
      - '.env.example'
  pull_request:
    branches: [main]
    paths:
      - 'Makefile'
      - 'scripts/**'
      - '.env.example'

jobs:
  test-glue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Shellcheck scripts
        run: shellcheck scripts/*.sh
      - name: Test Makefile syntax
        run: make -n install
